Document: openbfdd
Title: Debian openbfdd Manual
Author: <insert document author here>
Abstract: This manual describes what openbfdd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openbfdd/openbfdd.sgml.gz

Format: postscript
Files: /usr/share/doc/openbfdd/openbfdd.ps.gz

Format: text
Files: /usr/share/doc/openbfdd/openbfdd.text.gz

Format: HTML
Index: /usr/share/doc/openbfdd/html/index.html
Files: /usr/share/doc/openbfdd/html/*.html
